### ISSUE TITLE
Support for 1.20?

### ISSUE THREAD

**Issue by GeraldTM** [michiruf/MCServerPortals#3]

**Comment by michiruf** [comment]
Hi GeraldTM, its this time of the year where I can get back to stuff and now I implemented a multi version build. Feel free to take this over to your version as well if you want to!

Did you do any specific changes regarding functionality in your fork of the project?

EDIT: Versions currently supported are from 1.19 to 1.20.2, because after this, there is not customportalapi yet

**Comment by GeraldTM** [comment]
No, never got around to it

**Comment by michiruf** [comment]
Okay thanks for taking over then, Ill close this
